language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-22.0.1

script: ./gradlew clean assemble check

branches:
    only:
        - soundboardStructure