language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-android-m2repository

script: ./gradlew clean assemble check

branches:
    only:
        - soundboardStructure